spring:
  port: 8080
  application:
    name: sb-google-pub-sub
  cloud:
    gcp:
      project-id: silicon-guru-430007-u7
      credentials:
        location: classpath:silicon-guru-430007-u7-6b7901c537bd.json # location of GCP SA credentials
      pubsub:
        enabled: true